In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import re

In [2]:
def get_pl_name(x):
    pl_name = x.split('(')
    return pl_name[0]

In [3]:
def get_team(x):
    team_name = re.search('\(([^)]+)', x).group(1)
    return team_name

In [4]:
def indian(x):
    if str(x) == 'True':
        return 'indian'
    else:
        return 'foreign'

In [39]:
def is_opener(x):
    if int(x) <= 2:
        return 'Yes'
    else:
        return 'No'

In [40]:
df1 = pd.read_csv("ipl2020_indians.csv")
df2 = pd.read_csv("ipl2020_mostruns.csv")

## Requierement of this file is:
### The first file contains information about players who have scored 50 or more runs in IPL 2020 I want to work with this file and find out how many of them were openers and how many of them were non-openers.

### The second file contains information about Indian players who have scored 50 or more runs in IPL 2020.

### From the previous information that you extracted, I want you to find out how many those openers were Indians and how many of them were foreigners. And similarly find for non-openers.

## Please do this before we start today's class.

In [41]:
df1.head()

  Indian_Players
0     MA Agarwal
1       S Dhawan
2        PK Garg
3   Shubman Gill
4        SS Iyer

In [42]:
df2.head()

          Date                                   Player  Pos  Runs
0  19-Sep-2020        F du Plessis(Chennai Super Kings)    3    58
1  19-Sep-2020           AT Rayudu(Chennai Super Kings)    4    71
2  20-Sep-2020               MP Stoinis(Delhi Capitals)    6    53
3  20-Sep-2020              MA Agarwal(Kings XI Punjab)    2    89
4  21-Sep-2020  D Padikkal(Royal Challengers Bangalore)    1    56

In [43]:
df2.tail()

           Date                            Player  Pos  Runs
75  22-Oct-2020    V Shankar(Sunrisers Hyderabad)    4    52
76  23-Oct-2020    SM Curran(Chennai Super Kings)    7    52
77  23-Oct-2020      Ishan Kishan(Mumbai Indians)    2    68
78  24-Oct-2020     N Rana(Kolkata Knight Riders)    2    81
79  24-Oct-2020  SP Narine(Kolkata Knight Riders)    5    64

In [44]:
df2['Player_Name'] = df2['Player'].apply(get_pl_name)
print('Extracted players name :')
df2['Player_Name']

Extracted players name :

0     F du Plessis
1        AT Rayudu
2       MP Stoinis
3       MA Agarwal
4       D Padikkal
          ...
75       V Shankar
76       SM Curran
77    Ishan Kishan
78          N Rana
79       SP Narine
Name: Player_Name, Length: 80, dtype: object

In [45]:
df2['IPL_Teams'] = df2['Player'].apply(get_team)
df2['IPL_Teams']

0             Chennai Super Kings
1             Chennai Super Kings
2                  Delhi Capitals
3                 Kings XI Punjab
4     Royal Challengers Bangalore
                 ...
75            Sunrisers Hyderabad
76            Chennai Super Kings
77                 Mumbai Indians
78          Kolkata Knight Riders
79          Kolkata Knight Riders
Name: IPL_Teams, Length: 80, dtype: object

In [46]:
df2.head()

,Date,Player,Pos,Runs,Player_Name,IPL_Teams
0,19-Sep-2020,F du Plessis(Chennai Super Kings),3,58,F du Plessis,Chennai Super Kings
1,19-Sep-2020,AT Rayudu(Chennai Super Kings),4,71,AT Rayudu,Chennai Super Kings
2,20-Sep-2020,MP Stoinis(Delhi Capitals),6,53,MP Stoinis,Delhi Capitals
3,20-Sep-2020,MA Agarwal(Kings XI Punjab),2,89,MA Agarwal,Kings XI Punjab
4,21-Sep-2020,D Padikkal(Royal Challengers Bangalore),1,56,D Padikkal,Royal Challengers Bangalore

In [47]:
df1.head()

  Indian_Players
0     MA Agarwal
1       S Dhawan
2        PK Garg
3   Shubman Gill
4        SS Iyer

In [48]:
player = df1['Indian_Players'].tolist()

In [49]:
df2['Indian'] = df2['Player_Name'].isin(player)

In [50]:
df2.head()

,Date,Player,Pos,Runs,Player_Name,IPL_Teams,Indian
0,19-Sep-2020,F du Plessis(Chennai Super Kings),3,58,F du Plessis,Chennai Super Kings,False
1,19-Sep-2020,AT Rayudu(Chennai Super Kings),4,71,AT Rayudu,Chennai Super Kings,True
2,20-Sep-2020,MP Stoinis(Delhi Capitals),6,53,MP Stoinis,Delhi Capitals,False
3,20-Sep-2020,MA Agarwal(Kings XI Punjab),2,89,MA Agarwal,Kings XI Punjab,True
4,21-Sep-2020,D Padikkal(Royal Challengers Bangalore),1,56,D Padikkal,Royal Challengers Bangalore,True

In [87]:
df2['Indian_plr'] = df2['Indian'].apply(indian)
df2.head()

,Date,Player,Pos,Runs,Player_Name,IPL_Teams,Indian,Indian_plr,Opener
0,19-Sep-2020,F du Plessis(Chennai Super Kings),3,58,F du Plessis,Chennai Super Kings,False,foreign,No
1,19-Sep-2020,AT Rayudu(Chennai Super Kings),4,71,AT Rayudu,Chennai Super Kings,True,indian,No
2,20-Sep-2020,MP Stoinis(Delhi Capitals),6,53,MP Stoinis,Delhi Capitals,False,foreign,No
3,20-Sep-2020,MA Agarwal(Kings XI Punjab),2,89,MA Agarwal,Kings XI Punjab,True,indian,Yes
4,21-Sep-2020,D Padikkal(Royal Challengers Bangalore),1,56,D Padikkal,Royal Challengers Bangalore,True,indian,Yes

In [82]:
df2['Opener'] = df2['Pos'].apply(is_opener)

In [83]:
df = df2.drop(columns=['Indian'])

In [84]:
cols = df.columns.tolist()
cols

['Date',
 'Player',
 'Pos',
 'Runs',
 'Player_Name',
 'IPL_Teams',
 'Indian_plr',
 'Opener']

In [85]:
df = df[['Date','Player_Name','IPL_Teams','Indian_plr','Opener','Pos','Runs']]
df.head()

,Date,Player_Name,IPL_Teams,Indian_plr,Opener,Pos,Runs
0,19-Sep-2020,F du Plessis,Chennai Super Kings,foreign,No,3,58
1,19-Sep-2020,AT Rayudu,Chennai Super Kings,indian,No,4,71
2,20-Sep-2020,MP Stoinis,Delhi Capitals,foreign,No,6,53
3,20-Sep-2020,MA Agarwal,Kings XI Punjab,indian,Yes,2,89
4,21-Sep-2020,D Padikkal,Royal Challengers Bangalore,indian,Yes,1,56

####  Indian players who have scored 50 or more runs in IPL 2020

In [86]:
ind_df = df['Indian_plr'] == 'indian'
ind_df = df[ind_df]
ind_df.head()

,Date,Player_Name,IPL_Teams,Indian_plr,Opener,Pos,Runs
1,19-Sep-2020,AT Rayudu,Chennai Super Kings,indian,No,4,71
3,20-Sep-2020,MA Agarwal,Kings XI Punjab,indian,Yes,2,89
4,21-Sep-2020,D Padikkal,Royal Challengers Bangalore,indian,Yes,1,56
8,22-Sep-2020,SV Samson,Rajasthan Royals,indian,No,3,74
10,23-Sep-2020,RG Sharma,Mumbai Indians,indian,Yes,2,80

In [57]:
print('Total number of indian players scored more then fifty is :', ind_df.Runs.count(),'players')

Total number of indian players scored more then fifty is : 46 players

In [58]:
cc = df['Indian_plr'] == 'foreign'
foreign_plr = df[foreign_plr]
foreign_plr.head()

,Date,Player_Name,IPL_Teams,Indian_plr,Opener,Pos,Runs
0,19-Sep-2020,F du Plessis,Chennai Super Kings,foreign,No,3,58
2,20-Sep-2020,MP Stoinis,Delhi Capitals,foreign,No,6,53
5,21-Sep-2020,AB de Villiers,Royal Challengers Bangalore,foreign,No,4,51
6,21-Sep-2020,JM Bairstow,Sunrisers Hyderabad,foreign,Yes,2,61
7,22-Sep-2020,SPD Smith,Rajasthan Royals,foreign,Yes,2,69

In [88]:
print('Total number of foreign players scored more then fifty is :', foreign_plr.Runs.count(),'players')

Total number of foreign players scored more then fifty is : 34 players

### The first file contains information about players who have scored 50 or more runs in IPL 2020 I want to work with this file and find out how many of them were openers and how many of them were non-openers.

In [91]:
opener_bat = df['Opener'] == 'Yes'
opener_bat = df[opener_bat]
opener_bat.head()

,Date,Player_Name,IPL_Teams,Indian_plr,Opener,Pos,Runs
3,20-Sep-2020,MA Agarwal,Kings XI Punjab,indian,Yes,2,89
4,21-Sep-2020,D Padikkal,Royal Challengers Bangalore,indian,Yes,1,56
6,21-Sep-2020,JM Bairstow,Sunrisers Hyderabad,foreign,Yes,2,61
7,22-Sep-2020,SPD Smith,Rajasthan Royals,foreign,Yes,2,69
10,23-Sep-2020,RG Sharma,Mumbai Indians,indian,Yes,2,80

In [92]:
print('Total number openers are :', opener_bat.Runs.count(),'players')

Total number openers are : 42 players

In [93]:
non_opener_bat = df['Opener'] == 'No'
non_opener_bat = df[non_opener_bat]
non_opener_bat.head()

,Date,Player_Name,IPL_Teams,Indian_plr,Opener,Pos,Runs
0,19-Sep-2020,F du Plessis,Chennai Super Kings,foreign,No,3,58
1,19-Sep-2020,AT Rayudu,Chennai Super Kings,indian,No,4,71
2,20-Sep-2020,MP Stoinis,Delhi Capitals,foreign,No,6,53
5,21-Sep-2020,AB de Villiers,Royal Challengers Bangalore,foreign,No,4,51
8,22-Sep-2020,SV Samson,Rajasthan Royals,indian,No,3,74

In [96]:
print('Total number non_openers are :', non_opener_bat.Runs.count(),'players')

Total number non_openers are : 38 players

In [60]:
runs_50 = df['Runs'] > 49
runs_50 = df[runs_50]
runs_50.head()

,Date,Player_Name,IPL_Teams,Indian_plr,Opener,Pos,Runs
0,19-Sep-2020,F du Plessis,Chennai Super Kings,foreign,No,3,58
1,19-Sep-2020,AT Rayudu,Chennai Super Kings,indian,No,4,71
2,20-Sep-2020,MP Stoinis,Delhi Capitals,foreign,No,6,53
3,20-Sep-2020,MA Agarwal,Kings XI Punjab,indian,Yes,2,89
4,21-Sep-2020,D Padikkal,Royal Challengers Bangalore,indian,Yes,1,56

In [100]:
less_runs = df['Runs'] < 50
less_runs = df[less_runs]
print('There is no players scored less then 50 Runs')
less_runs.head()

There is no players scored less then 50 Runs

Empty DataFrame
Columns: [Date, Player_Name, IPL_Teams, Indian_plr, Opener, Pos, Runs]
Index: []

### From the previous information that you extracted, I want you to find out how many those openers were Indians and how many of them were foreigners. And similarly find for non-openers.

In [102]:
opener_bat.head()

,Date,Player_Name,IPL_Teams,Indian_plr,Opener,Pos,Runs
3,20-Sep-2020,MA Agarwal,Kings XI Punjab,indian,Yes,2,89
4,21-Sep-2020,D Padikkal,Royal Challengers Bangalore,indian,Yes,1,56
6,21-Sep-2020,JM Bairstow,Sunrisers Hyderabad,foreign,Yes,2,61
7,22-Sep-2020,SPD Smith,Rajasthan Royals,foreign,Yes,2,69
10,23-Sep-2020,RG Sharma,Mumbai Indians,indian,Yes,2,80

In [116]:
ind_opener = opener_bat['Indian_plr'] == 'indian'
ind_opener = opener_bat[ind_opener]
ind_opener.head()

,Date,Player_Name,IPL_Teams,Indian_plr,Opener,Pos,Runs
3,20-Sep-2020,MA Agarwal,Kings XI Punjab,indian,Yes,2,89
4,21-Sep-2020,D Padikkal,Royal Challengers Bangalore,indian,Yes,1,56
10,23-Sep-2020,RG Sharma,Mumbai Indians,indian,Yes,2,80
11,24-Sep-2020,KL Rahul,Kings XI Punjab,indian,Yes,1,132
12,25-Sep-2020,PP Shaw,Delhi Capitals,indian,Yes,1,64

In [120]:
print('Total Indian Openers are :',ind_opener.Player_Name.count(),'players')

Total Indian Openers are : 25 players

In [124]:
frn_opener = opener_bat['Indian_plr'] == 'foreign'
frn_opener = opener_bat[frn_opener]
frn_opener.head()

,Date,Player_Name,IPL_Teams,Indian_plr,Opener,Pos,Runs
6,21-Sep-2020,JM Bairstow,Sunrisers Hyderabad,foreign,Yes,2,61
7,22-Sep-2020,SPD Smith,Rajasthan Royals,foreign,Yes,2,69
17,27-Sep-2020,SPD Smith,Rajasthan Royals,foreign,Yes,2,50
21,28-Sep-2020,AJ Finch,Royal Challengers Bangalore,foreign,Yes,2,52
25,29-Sep-2020,JM Bairstow,Sunrisers Hyderabad,foreign,Yes,2,53

In [125]:
print('Total Indian Openers are :',frn_opener.Player_Name.count(),'players')

Total Indian Openers are : 17 players

### Non opener indians and foreign payers are:

In [126]:
ind_non_opener = non_opener_bat['Indian_plr'] == 'indian'
ind_non_opener = non_opener_bat[ind_non_opener]
ind_non_opener.head()

           Date Player_Name            IPL_Teams Indian_plr Opener  Pos  Runs
1   19-Sep-2020   AT Rayudu  Chennai Super Kings     indian     No    4    71
8   22-Sep-2020   SV Samson     Rajasthan Royals     indian     No    3    74
13  26-Sep-2020   MK Pandey  Sunrisers Hyderabad     indian     No    3    51
18  27-Sep-2020   SV Samson     Rajasthan Royals     indian     No    3    85
19  27-Sep-2020   R Tewatia     Rajasthan Royals     indian     No    4    53

In [127]:
print('Total Indian non_Openers are :',ind_non_opener.Player_Name.count(),'players')

Total Indian non_Openers are : 21 players

In [129]:
frn_non_opener = non_opener_bat['Indian_plr'] == 'foreign'
frn_non_opener = non_opener_bat[frn_non_opener]
frn_non_opener.head()

,Date,Player_Name,IPL_Teams,Indian_plr,Opener,Pos,Runs
0,19-Sep-2020,F du Plessis,Chennai Super Kings,foreign,No,3,58
2,20-Sep-2020,MP Stoinis,Delhi Capitals,foreign,No,6,53
5,21-Sep-2020,AB de Villiers,Royal Challengers Bangalore,foreign,No,4,51
9,22-Sep-2020,F du Plessis,Chennai Super Kings,foreign,No,3,72
22,28-Sep-2020,AB de Villiers,Royal Challengers Bangalore,foreign,No,4,55

In [130]:
print('Total Indian non_Openers are :',frn_non_opener.Player_Name.count(),'players')

Total Indian non_Openers are : 17 players

## Thank you